"""create retail analytics schema

Revision ID: 4b9f67039f0b
Revises:
Create Date: 2026-08-23 14:46:35.693456
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "4b9f67039f0b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    op.execute('CREATE SCHEMA "retail"')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column(
            "id",
            sa.SmallInteger(),
            sa.Identity(always=False),
            nullable=False,
            comment="Surrogate category identifier.",
        ),
        sa.Column("name", sa.String(length=100), nullable=False, comment="Unique category name."),
        sa.Column(
            "description",
            sa.String(length=500),
            nullable=True,
            comment="Business description of the category.",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_categories")),
        sa.UniqueConstraint("name", name=op.f("uq_categories_name")),
        schema="retail",
        comment="Product category hierarchy root.",
    )
    op.create_table(
        "regions",
        sa.Column(
            "id",
            sa.SmallInteger(),
            sa.Identity(always=False),
            nullable=False,
            comment="Surrogate region identifier.",
        ),
        sa.Column(
            "code",
            sa.String(length=16),
            nullable=False,
            comment="Stable business code for the region.",
        ),
        sa.Column(
            "name", sa.String(length=80), nullable=False, comment="Human-readable region name."
        ),
        sa.Column(
            "country_code",
            sa.String(length=2),
            server_default=sa.text("'BR'"),
            nullable=False,
            comment="ISO 3166-1 alpha-2 country code.",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_regions")),
        sa.UniqueConstraint("code", name=op.f("uq_regions_code")),
        sa.UniqueConstraint("name", name=op.f("uq_regions_name")),
        schema="retail",
        comment="Brazilian sales regions.",
    )
    op.create_table(
        "customers",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
            comment="Surrogate customer identifier.",
        ),
        sa.Column(
            "external_id",
            sa.Uuid(),
            nullable=False,
            comment="Public UUID used outside the database.",
        ),
        sa.Column("region_id", sa.SmallInteger(), nullable=False, comment="Customer home region."),
        sa.Column(
            "full_name", sa.String(length=160), nullable=False, comment="Synthetic customer name."
        ),
        sa.Column(
            "email",
            sa.String(length=254),
            nullable=False,
            comment="Synthetic email; treated as a restricted column.",
        ),
        sa.Column(
            "document_number",
            sa.String(length=32),
            nullable=True,
            comment="Synthetic document; always restricted from NL2SQL.",
        ),
        sa.Column(
            "segment", sa.String(length=24), nullable=False, comment="Commercial customer segment."
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Whether the customer is active.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Customer creation timestamp.",
        ),
        sa.CheckConstraint(
            "segment IN ('consumer', 'small_business', 'enterprise')",
            name=op.f("ck_customers_segment_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["retail.regions.id"],
            name=op.f("fk_customers_region_id_regions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_customers")),
        sa.UniqueConstraint("email", name=op.f("uq_customers_email")),
        sa.UniqueConstraint("external_id", name=op.f("uq_customers_external_id")),
        schema="retail",
        comment="Synthetic customers used by the retail analytics demo.",
    )
    op.create_index(
        "ix_customers_created_at", "customers", ["created_at"], unique=False, schema="retail"
    )
    op.create_index(
        "ix_customers_region_id", "customers", ["region_id"], unique=False, schema="retail"
    )
    op.create_table(
        "products",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
            comment="Surrogate product identifier.",
        ),
        sa.Column("category_id", sa.SmallInteger(), nullable=False, comment="Product category."),
        sa.Column(
            "sku", sa.String(length=40), nullable=False, comment="Stable stock keeping unit."
        ),
        sa.Column("name", sa.String(length=180), nullable=False, comment="Product display name."),
        sa.Column(
            "unit_cost",
            sa.Numeric(precision=14, scale=2),
            nullable=False,
            comment="Reference acquisition cost in BRL.",
        ),
        sa.Column(
            "list_price",
            sa.Numeric(precision=14, scale=2),
            nullable=False,
            comment="Reference list price in BRL.",
        ),
        sa.Column(
            "active",
            sa.Boolean(),
            server_default=sa.text("true"),
            nullable=False,
            comment="Whether the product is available for sale.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Product creation timestamp.",
        ),
        sa.CheckConstraint("list_price > 0", name=op.f("ck_products_list_price_positive")),
        sa.CheckConstraint("unit_cost >= 0", name=op.f("ck_products_unit_cost_nonnegative")),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["retail.categories.id"],
            name=op.f("fk_products_category_id_categories"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("sku", name=op.f("uq_products_sku")),
        schema="retail",
        comment="Products sold by the demonstration store.",
    )
    op.create_index("ix_products_active", "products", ["active"], unique=False, schema="retail")
    op.create_index(
        "ix_products_category_id", "products", ["category_id"], unique=False, schema="retail"
    )
    op.create_table(
        "sales_targets",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
            comment="Surrogate sales-target identifier.",
        ),
        sa.Column(
            "region_id", sa.SmallInteger(), nullable=False, comment="Region receiving the target."
        ),
        sa.Column(
            "target_month",
            sa.Date(),
            nullable=False,
            comment="First calendar day of the target month.",
        ),
        sa.Column(
            "revenue_target",
            sa.Numeric(precision=16, scale=2),
            nullable=False,
            comment="Monthly net-revenue target in BRL.",
        ),
        sa.Column(
            "orders_target", sa.Integer(), nullable=False, comment="Monthly completed-order target."
        ),
        sa.CheckConstraint(
            "EXTRACT(DAY FROM target_month) = 1",
            name=op.f("ck_sales_targets_month_starts_on_first_day"),
        ),
        sa.CheckConstraint(
            "orders_target > 0", name=op.f("ck_sales_targets_orders_target_positive")
        ),
        sa.CheckConstraint(
            "revenue_target > 0", name=op.f("ck_sales_targets_revenue_target_positive")
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["retail.regions.id"],
            name=op.f("fk_sales_targets_region_id_regions"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sales_targets")),
        sa.UniqueConstraint("region_id", "target_month", name=op.f("uq_sales_targets_region_id")),
        schema="retail",
        comment="Monthly revenue and order targets by region.",
    )
    op.create_index(
        "ix_sales_targets_region_id", "sales_targets", ["region_id"], unique=False, schema="retail"
    )
    op.create_index(
        "ix_sales_targets_target_month",
        "sales_targets",
        ["target_month"],
        unique=False,
        schema="retail",
    )
    op.create_table(
        "orders",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
            comment="Surrogate order identifier.",
        ),
        sa.Column(
            "order_number",
            sa.String(length=32),
            nullable=False,
            comment="Stable business order number.",
        ),
        sa.Column(
            "customer_id", sa.BigInteger(), nullable=False, comment="Customer who placed the order."
        ),
        sa.Column(
            "region_id",
            sa.SmallInteger(),
            nullable=False,
            comment="Sales region attributed at order time.",
        ),
        sa.Column(
            "placed_at",
            sa.DateTime(timezone=True),
            nullable=False,
            comment="Timestamp when the order was placed.",
        ),
        sa.Column(
            "status",
            sa.String(length=20),
            nullable=False,
            comment="Current order lifecycle status.",
        ),
        sa.Column(
            "channel",
            sa.String(length=20),
            nullable=False,
            comment="Sales channel used by the customer.",
        ),
        sa.Column(
            "discount_amount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
            comment="Order-level discount in BRL.",
        ),
        sa.Column(
            "shipping_amount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
            comment="Shipping charge in BRL.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Database creation timestamp.",
        ),
        sa.CheckConstraint(
            "channel IN ('web', 'mobile', 'store', 'marketplace')",
            name=op.f("ck_orders_channel_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'paid', 'shipped', 'delivered', 'cancelled')",
            name=op.f("ck_orders_status_allowed"),
        ),
        sa.CheckConstraint("discount_amount >= 0", name=op.f("ck_orders_discount_nonnegative")),
        sa.CheckConstraint("shipping_amount >= 0", name=op.f("ck_orders_shipping_nonnegative")),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["retail.customers.id"],
            name=op.f("fk_orders_customer_id_customers"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["region_id"],
            ["retail.regions.id"],
            name=op.f("fk_orders_region_id_regions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint("order_number", name=op.f("uq_orders_order_number")),
        schema="retail",
        comment="E-commerce and retail sales orders.",
    )
    op.create_index(
        "ix_orders_customer_id", "orders", ["customer_id"], unique=False, schema="retail"
    )
    op.create_index("ix_orders_placed_at", "orders", ["placed_at"], unique=False, schema="retail")
    op.create_index("ix_orders_region_id", "orders", ["region_id"], unique=False, schema="retail")
    op.create_index("ix_orders_status", "orders", ["status"], unique=False, schema="retail")
    op.create_table(
        "order_items",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
            comment="Surrogate order-item identifier.",
        ),
        sa.Column("order_id", sa.BigInteger(), nullable=False, comment="Parent order."),
        sa.Column("product_id", sa.BigInteger(), nullable=False, comment="Product sold."),
        sa.Column("quantity", sa.Integer(), nullable=False, comment="Number of units sold."),
        sa.Column(
            "unit_price",
            sa.Numeric(precision=14, scale=2),
            nullable=False,
            comment="Unit sale price snapshot in BRL.",
        ),
        sa.Column(
            "unit_cost",
            sa.Numeric(precision=14, scale=2),
            nullable=False,
            comment="Unit cost snapshot in BRL.",
        ),
        sa.Column(
            "discount_amount",
            sa.Numeric(precision=14, scale=2),
            server_default=sa.text("0"),
            nullable=False,
            comment="Line-level discount in BRL.",
        ),
        sa.CheckConstraint(
            "discount_amount <= quantity * unit_price",
            name=op.f("ck_order_items_discount_not_above_gross"),
        ),
        sa.CheckConstraint(
            "discount_amount >= 0", name=op.f("ck_order_items_discount_nonnegative")
        ),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_order_items_quantity_positive")),
        sa.CheckConstraint("unit_cost >= 0", name=op.f("ck_order_items_unit_cost_nonnegative")),
        sa.CheckConstraint("unit_price > 0", name=op.f("ck_order_items_unit_price_positive")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["retail.orders.id"],
            name=op.f("fk_order_items_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["retail.products.id"],
            name=op.f("fk_order_items_product_id_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_order_items")),
        schema="retail",
        comment="Line items with price and cost snapshots.",
    )
    op.create_index(
        "ix_order_items_order_id", "order_items", ["order_id"], unique=False, schema="retail"
    )
    op.create_index(
        "ix_order_items_product_id", "order_items", ["product_id"], unique=False, schema="retail"
    )
    op.create_table(
        "payments",
        sa.Column(
            "id",
            sa.BigInteger(),
            sa.Identity(always=False),
            nullable=False,
            comment="Surrogate payment identifier.",
        ),
        sa.Column(
            "order_id",
            sa.BigInteger(),
            nullable=False,
            comment="Order associated with the payment.",
        ),
        sa.Column(
            "transaction_reference",
            sa.String(length=80),
            nullable=False,
            comment="Synthetic payment-provider reference.",
        ),
        sa.Column("method", sa.String(length=24), nullable=False, comment="Payment method."),
        sa.Column(
            "status", sa.String(length=20), nullable=False, comment="Payment processing status."
        ),
        sa.Column(
            "amount",
            sa.Numeric(precision=14, scale=2),
            nullable=False,
            comment="Payment amount in BRL.",
        ),
        sa.Column(
            "paid_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Settlement timestamp when approved.",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
            comment="Payment creation timestamp.",
        ),
        sa.CheckConstraint(
            "method IN ('credit_card', 'debit_card', 'pix', 'bank_slip')",
            name=op.f("ck_payments_method_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'approved', 'failed', 'refunded')",
            name=op.f("ck_payments_status_allowed"),
        ),
        sa.CheckConstraint("amount > 0", name=op.f("ck_payments_amount_positive")),
        sa.ForeignKeyConstraint(
            ["order_id"],
            ["retail.orders.id"],
            name=op.f("fk_payments_order_id_orders"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint(
            "transaction_reference", name=op.f("uq_payments_transaction_reference")
        ),
        schema="retail",
        comment="Payment attempts and successful settlements.",
    )
    op.create_index("ix_payments_order_id", "payments", ["order_id"], unique=False, schema="retail")
    op.create_index("ix_payments_paid_at", "payments", ["paid_at"], unique=False, schema="retail")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_payments_paid_at", table_name="payments", schema="retail")
    op.drop_index("ix_payments_order_id", table_name="payments", schema="retail")
    op.drop_table("payments", schema="retail")
    op.drop_index("ix_order_items_product_id", table_name="order_items", schema="retail")
    op.drop_index("ix_order_items_order_id", table_name="order_items", schema="retail")
    op.drop_table("order_items", schema="retail")
    op.drop_index("ix_orders_status", table_name="orders", schema="retail")
    op.drop_index("ix_orders_region_id", table_name="orders", schema="retail")
    op.drop_index("ix_orders_placed_at", table_name="orders", schema="retail")
    op.drop_index("ix_orders_customer_id", table_name="orders", schema="retail")
    op.drop_table("orders", schema="retail")
    op.drop_index("ix_sales_targets_target_month", table_name="sales_targets", schema="retail")
    op.drop_index("ix_sales_targets_region_id", table_name="sales_targets", schema="retail")
    op.drop_table("sales_targets", schema="retail")
    op.drop_index("ix_products_category_id", table_name="products", schema="retail")
    op.drop_index("ix_products_active", table_name="products", schema="retail")
    op.drop_table("products", schema="retail")
    op.drop_index("ix_customers_region_id", table_name="customers", schema="retail")
    op.drop_index("ix_customers_created_at", table_name="customers", schema="retail")
    op.drop_table("customers", schema="retail")
    op.drop_table("regions", schema="retail")
    op.drop_table("categories", schema="retail")
    op.execute('DROP SCHEMA "retail"')
    # ### end Alembic commands ###
